init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.1.{build}-{branch}
artifacts:
  - path: SampleUsage/SampleInput.Lenses/*.fs*
    name: LensFiles

  - path: SampleUsage/SampleUsage/bin
    name: bin